# Generated by Django 6.0.3 on 2026-04-10 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_point_owner_alter_point_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='Владелец пункта'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PointWastePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.point')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wastetype')),
            ],
            options={
                'unique_together': {('point', 'waste_type')},
            },
        ),
    ]
