# Generated by Django 6.0.3 on 2026-04-13 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_point_owner_pointwasteprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='point',
            name='legal_entity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИП / ООО'),
        ),
        migrations.AddField(
            model_name='point',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='point',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='Владелец бизнеса'),
        ),
    ]
