# Generated by Django 6.0.3 on 2026-04-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_point_inn_point_legal_entity_point_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_business',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
