# Generated by Django 6.0.3 on 2026-04-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_is_business_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointwasteprice',
            options={'verbose_name': 'Цена на отход', 'verbose_name_plural': 'Цены на отходы'},
        ),
        migrations.AlterUniqueTogether(
            name='pointwasteprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='point',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (общая информация)'),
        ),
        migrations.AddField(
            model_name='point',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон для связи'),
        ),
        migrations.AddField(
            model_name='point',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='pointwasteprice',
            name='item_spec',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Уточнение (например, 'Ящики из-под фруктов' или 'Пленка')"),
        ),
        migrations.AddField(
            model_name='pointwasteprice',
            name='unit',
            field=models.CharField(default='кг', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='pointwasteprice',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед. (руб.)'),
        ),
        migrations.AlterField(
            model_name='pointwasteprice',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wastetype', verbose_name='Тип отхода'),
        ),
    ]
