# Generated by Django 6.0.3 on 2026-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pointwasteprice_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text="Пример: {'пн': '08:00-20:00', 'сб': '10:00-15:00', 'вс': 'выходной'}", null=True, verbose_name='Режим работы (по дням)'),
        ),
    ]
