# Generated by Django 6.0.3 on 2026-04-18 12:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_point_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты (локация)'),
        ),
    ]
