# Generated by Django 6.0.3 on 2026-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pointwasteprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointwasteprice',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Принимается сейчас'),
        ),
    ]
