# Generated by Django 6.0.3 on 2026-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_point_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text="Пример: {''пн'': ''08:00-20:00'', ''сб'': ''10:00-15:00'', ''вс'': ''выходной''} (Использовать двойные кавычки)", null=True, verbose_name='Режим работы (по дням)'),
        ),
    ]
