# Generated by Django 6.0.3 on 2026-04-25 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_point_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='accepted_waste',
        ),
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='point',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='point',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='point',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='pointwasteprice',
            name='item_spec',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уточнение'),
        ),
        migrations.AlterField(
            model_name='pointwasteprice',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='pointwasteprice',
            name='unit',
            field=models.CharField(default='кг', max_length=20, verbose_name='Единица'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка (1-5)')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.point', verbose_name='Точка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
