# Generated by Django 6.0.3 on 2026-05-04 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_is_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastetype',
            options={'verbose_name': 'Наименование отхода', 'verbose_name_plural': 'Отходы/Сырье'},
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Тип отходов/сырья'),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (например, Ящик для фруктов (б/у))'),
        ),
        migrations.CreateModel(
            name='PointReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(verbose_name='Это лайк?')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.point', verbose_name='Точка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция на пункт',
                'verbose_name_plural': 'Реакции на пункты',
                'unique_together': {('user', 'point')},
            },
        ),
    ]
