# Generated by Django 6.0.3 on 2026-05-04 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_wastetype_options_alter_wastetype_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointEditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст исправления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Рассмотрено')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to='api.point', verbose_name='Точка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предложенное исправление',
                'verbose_name_plural': 'Предложенные исправления',
            },
        ),
    ]
