# Generated by Django 6.0.3 on 2026-05-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pointeditsuggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointeditsuggestion',
            options={'verbose_name': 'Исправления', 'verbose_name_plural': 'Исправления'},
        ),
        migrations.AddField(
            model_name='point',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='point',
            name='useful_links',
            field=models.TextField(blank=True, null=True, verbose_name='Полезные ссылки'),
        ),
    ]
