# Generated by Django 6.0.3 on 2026-05-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_articlecategory_user_is_author_article'),
        ('api', '0017_alter_pointeditsuggestion_options_point_site_and_more'),
    ]

    operations = [
    ]
