# Generated by Django 6.0.3 on 2026-05-04 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20260504_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointeditsuggestion',
            options={'verbose_name': 'Исправление', 'verbose_name_plural': 'Исправления'},
        ),
        migrations.AlterModelOptions(
            name='pointreaction',
            options={'verbose_name': 'Реакция'},
        ),
        migrations.AlterField(
            model_name='article',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/audio/', verbose_name='Аудиофайл'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='pointeditsuggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pointeditsuggestion',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to='api.point'),
        ),
        migrations.AlterField(
            model_name='pointeditsuggestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointreaction',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.point'),
        ),
        migrations.AlterField(
            model_name='pointreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (например, Ящик для фруктов)'),
        ),
    ]
