# Generated by Django 6.0.3 on 2026-05-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_pointeditsuggestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='waste_types',
            field=models.ManyToManyField(blank=True, related_name='articles', to='api.wastetype', verbose_name='Теги сырья'),
        ),
    ]
